name: Sync branch stable
on:
  push:
    branches:
      - incubation

jobs:
  sync-branches:
    if: ${{ github.repository == 'opendatahub-io/llama-stack-provider-trustyai-garak' }}
    runs-on: ubuntu-latest
    name: Syncing branch stable
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "incubation"
          TO_BRANCH: "stable"
      - name: Add labels
        if: ${{ steps.pull.outputs.PULL_REQUEST_NUMBER != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{steps.pull.outputs.PULL_REQUEST_NUMBER}},
              labels: ['bot/sync-stable', 'tide/merge-method-merge']
            });